---
driver:
  name: vagrant

provisioner:
  name: salt_solo
  formula: mariadb
  state_top:
        - mariadb
  state_collection: True


platforms:
  - name: centos-7.0

suites:
  - name: default
    run_list:
    attributes:
