---
driver:
  name: vagrant

provisioner:
  name: salt_solo
  formula: mariadb
  state_top:
    base:
      '*':
        - mariadb

platforms:
  - name: ubuntu-14.10
  - name: centos-7.0

suites:
  - name: default
    
